[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solanox = "8ThKqoTws1H2vAAWUUAnTKqQcLkCdc6Ua7GRyUhegqY1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/john/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
